name: Update
on:
  schedule:
    - cron: '0 1,13,19 * * *'
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: update data
        run: |
          python update/update.py
      - name: commit
        run: |
          git config --global user.email covid-bot@example.com"
          git config --global user.name "covid-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualización"; git push -q "https://$GH_TOKEN@github.com/mauforonda/super_magic_covid_middleware.git" master)
